[tool.black]
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | example-code

  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
)/
'''
